name: "Github Actions Activity"

# Defines when the workflow will run
on:
  # Manual trigger using GitHub Actions UI
  workflow_dispatch:
    inputs:
      # Input parameter to choose between apply or destroy actions
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - Terraform_apply
        - Terraform_destroy

jobs:

  terraform:
    # Job label shows which action was selected
    name: "Terraform (${{ github.event.inputs.action }})"
    # Use GitHub-hosted Ubuntu runner
    runs-on: ubuntu-latest
    
    env:
     TF_VAR_aws_region: ${{ vars.AWS_REGION }}
     TF_VAR_key_name: ${{ secrets.KEY_NAME }}
     TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
     TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    
    steps:
      # Pull the repo so Terraform files are available
      - name: Checkout repository
        uses: actions/checkout@v4
  
      # Configure AWS creds for Terraform to access AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
        
      # Install the specified Terraform version
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false

      # Write the S3 backend configuration file
      - name: Write S3 backend block
        run: |
          cat > backend.tf <<'EOF'
          terraform {
            backend "s3" {}
            }
          EOF


      - name: Debug bucket/key values
        run: |
          echo "BUCKET=[${{ vars.TF_STATE_BUCKET }}]"
          echo "KEY=[${{ vars.TF_STATE_KEY }}]"

      # Initialize providers and backend
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{vars.TF_STATE_BUCKET}}" -backend-config="key=${{vars.TF_STATE_KEY}}" -backend-config="region=${{vars.AWS_REGION}}" -backend-config="encrypt=true"
      # Show the execution plan when applying
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'Terraform_apply' }}
        run: terraform plan

      # Apply changes to AWS when applying
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'Terraform_apply' }}
        run: terraform apply -auto-approve
      # Output 
      - name: Terraform Output
        if: ${{ github.event.inputs.action == 'Terraform_apply' }}
        run: terraform output
        
      # Destroy resources in AWS when destroying
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
        run: terraform destroy -auto-approve
